// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"personal_page/config"
	"personal_page/delivery"
	"personal_page/repository/database/mysql"
	"personal_page/repository/driver"
	"personal_page/usecase"
)

// Injectors from wire.go:

func InitializeServer() *delivery.WebDeli {
	viper := config.Get()
	db := driver.GetMYSQL(viper)
	userRepository := mysql.NewUserRepository(db)
	tokenUsecase := usecase.NewTokenUsecase(userRepository)
	todoRepository := mysql.NewTodoRepository(db)
	todoUsecase := usecase.NewTodoUsecase(todoRepository)
	planRepository := mysql.NewPlanRepository(db)
	planUsecase := usecase.NewPlanUsecase(planRepository)
	webDeli := delivery.NewWebDeli(viper, tokenUsecase, todoUsecase, planUsecase)
	return webDeli
}
