// Code generated by goctl. DO NOT EDIT.
package types

type MemoCreateReq struct {
	Content string `json:"content" require:"true"`
}

type MemoDeleteReq struct {
	Id uint `json:"id" require:"true"`
}

type MemoItem struct {
	Id      uint   `json:"id" require:"true"`
	Content string `json:"content" require:"true"`
}

type MemoListResp struct {
	Memoes []MemoItem `json:"memoes"`
}
