// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "tiny beer",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/plan": {
            "get": {
                "description": "使用access_token获取Plan列表资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Plan相关接口"
                ],
                "summary": "获取Plan列表资源",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PlanListResp"
                        }
                    }
                }
            },
            "post": {
                "description": "使用access_token创建Plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Plan相关接口"
                ],
                "summary": "根据内容创建新的Plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "TODO创建参数",
                        "name": "{object}",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PlanCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.BaseResp"
                        }
                    }
                }
            },
            "delete": {
                "description": "使用access_token删除指定id的Plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TODO相关接口"
                ],
                "summary": "根据Id删除Plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "TODO删除参数",
                        "name": "{object}",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PlanDeleteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.BaseResp"
                        }
                    }
                }
            }
        },
        "/todo": {
            "get": {
                "description": "使用access_token获取TODO列表资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TODO相关接口"
                ],
                "summary": "获取TODO列表资源",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TodoListResp"
                        }
                    }
                }
            },
            "put": {
                "description": "使用access_token根据ID更新TODO完成时间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TODO相关接口"
                ],
                "summary": "根据ID更新TODO完成时间",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "TODO完成参数",
                        "name": "{object}",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.TodoCompleteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.BaseResp"
                        }
                    }
                }
            },
            "post": {
                "description": "使用access_token创建TODO",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TODO相关接口"
                ],
                "summary": "根据内容创建新的TODO",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "TODO创建参数",
                        "name": "{object}",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.TodoCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.BaseResp"
                        }
                    }
                }
            },
            "delete": {
                "description": "使用access_token删除指定id的TODO",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TODO相关接口"
                ],
                "summary": "根据Id删除TOOD",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "TODO删除参数",
                        "name": "{object}",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.TodoDeleteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.BaseResp"
                        }
                    }
                }
            }
        },
        "/token": {
            "post": {
                "description": "完成用户登陆操作分发access_token和refresh_token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TOKEN相关接口"
                ],
                "summary": "用于用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "{object}",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.TokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TokenResp"
                        }
                    }
                }
            }
        },
        "/token/access_token": {
            "post": {
                "description": "使用refresh_token更新访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "更新访问令牌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "refresh_token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AccessTokenResp"
                        }
                    }
                }
            }
        },
        "/token/check": {
            "get": {
                "description": "使用access_token验证用户身份",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "验证用户身份",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.BaseResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AccessTokenResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "domain.BaseResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "domain.Plan": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "times": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/domain.PlanType"
                }
            }
        },
        "domain.PlanCreateReq": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "times": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/domain.PlanType"
                }
            }
        },
        "domain.PlanDeleteReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.PlanListResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Plan"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "domain.PlanType": {
            "type": "string",
            "enum": [
                "daily",
                "weekly",
                "monthly"
            ],
            "x-enum-varnames": [
                "PlanType_Daily",
                "PlanType_Weekly",
                "PlanType_Monthly"
            ]
        },
        "domain.Todo": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "completeted_times": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "times": {
                    "type": "integer"
                }
            }
        },
        "domain.TodoCompleteReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.TodoCreateReq": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "times": {
                    "type": "integer"
                }
            }
        },
        "domain.TodoDeleteReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.TodoListResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Todo"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "domain.TokenReq": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 18,
                    "minLength": 3
                },
                "username": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 4
                }
            }
        },
        "domain.TokenResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:9999",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "个人主页",
	Description:      "用于个人文件管理",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
